- hosts: all
  tasks:
    - name: Copy Terraform template
	  copy:
        src: /terraform/templates/prod-2vm-stack.tf
        dest: /terraform/stacks/{{project}}/prod-vm-stack.tf
        remote_src: true